name: easy_graphql
description: This is a flutter library that makes it easy to work with graphql queries, mutations and subscriptions.
version: 1.0.0
homepage: https://github.com/cyenite/easy-graphql

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

